// AUTO-GENERATED by `pnpm meta:generate` — do not edit by hand.
// Structural metrics derived from each question's canonical solution.
import type { QuestionMetrics } from './metrics';

export const questionMetadata: Record<string, QuestionMetrics> = {
  "q-orders-by-status": {"tables":["orders"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-completed-avg-order-value": {"tables":["orders"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":false,"orderBy":false,"distinct":false},
  "q-products-in-category": {"tables":["products"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":0,"subqueries":0,"groupBy":false,"orderBy":true,"distinct":false},
  "q-distinct-purchasers": {"tables":["events"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":false,"orderBy":false,"distinct":false},
  "q-events-per-day": {"tables":["events"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-active-subscriptions": {"tables":["subscriptions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":false,"orderBy":false,"distinct":false},
  "q-churned-customers": {"tables":["subscriptions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":0,"subqueries":0,"groupBy":false,"orderBy":true,"distinct":false},
  "q-arpu-active": {"tables":["subscriptions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":false,"orderBy":false,"distinct":false},
  "q-sessions-per-channel": {"tables":["sessions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-customer-completed-revenue": {"tables":["customers","orders"],"tableCount":2,"joins":1,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-units-sold-per-product": {"tables":["order_items","orders","products"],"tableCount":3,"joins":2,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-revenue-by-category": {"tables":["order_items","orders","products"],"tableCount":3,"joins":2,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-mrr-by-plan": {"tables":["subscriptions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-avg-items-per-order": {"tables":["order_items","orders"],"tableCount":2,"joins":1,"windowFunctions":0,"ctes":1,"aggregates":2,"subqueries":0,"groupBy":true,"orderBy":false,"distinct":false},
  "q-second-highest-order": {"tables":["orders"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":0,"subqueries":0,"groupBy":false,"orderBy":true,"distinct":false},
  "q-customers-without-completed-orders": {"tables":["customers","orders"],"tableCount":2,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":0,"subqueries":1,"groupBy":false,"orderBy":true,"distinct":false},
  "q-distinct-events-dedup": {"tables":["events"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":1,"groupBy":false,"orderBy":false,"distinct":true},
  "q-first-event-per-user": {"tables":["events"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-customer-spend-rank": {"tables":["customers","orders"],"tableCount":2,"joins":1,"windowFunctions":1,"ctes":0,"aggregates":2,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-running-revenue-by-day": {"tables":["orders"],"tableCount":1,"joins":0,"windowFunctions":1,"ctes":0,"aggregates":2,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-time-between-events": {"tables":["events"],"tableCount":1,"joins":0,"windowFunctions":1,"ctes":0,"aggregates":0,"subqueries":0,"groupBy":false,"orderBy":true,"distinct":false},
  "q-top-completed-order-per-customer": {"tables":["customers","orders"],"tableCount":2,"joins":1,"windowFunctions":1,"ctes":0,"aggregates":0,"subqueries":0,"groupBy":false,"orderBy":true,"distinct":false},
  "q-funnel-signup-to-purchase": {"tables":["events"],"tableCount":1,"joins":1,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":1,"groupBy":true,"orderBy":false,"distinct":false},
  "q-signups-by-month-cohort": {"tables":["subscriptions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":1,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
  "q-first-touch-attribution": {"tables":["sessions"],"tableCount":1,"joins":0,"windowFunctions":1,"ctes":2,"aggregates":1,"subqueries":1,"groupBy":true,"orderBy":true,"distinct":true},
  "q-conversion-rate-by-channel": {"tables":["sessions"],"tableCount":1,"joins":0,"windowFunctions":0,"ctes":0,"aggregates":2,"subqueries":0,"groupBy":true,"orderBy":true,"distinct":false},
};
