/**
 * SQL-feature coverage tracker. Runs each feature's detector over every
 * question's canonical solution and writes COVERAGE.md — a live checklist with
 * per-feature question counts. Run: pnpm coverage
 */
import { writeFileSync } from 'node:fs';
import { questions } from '../src/content/node';
import { FEATURES, CATEGORIES } from '../src/content/features';

interface Row {
  feature: (typeof FEATURES)[number];
  count: number;
  ids: string[];
}

const rows: Row[] = FEATURES.map((feature) => {
  const matched = questions.filter((q) => {
    if (q.features?.includes(feature.id)) return true; // manual tag (detection can't infer, e.g. self-join)
    const sql = (q.canonical.generic ?? '').toUpperCase().replace(/\s+/g, ' ');
    try {
      return feature.detect(sql);
    } catch {
      return false;
    }
  });
  return { feature, count: matched.length, ids: matched.map((q) => q.slug) };
});

const covered = rows.filter((r) => r.count > 0).length;
const lines: string[] = [
  '# SQL feature coverage',
  '',
  '> Auto-generated by `pnpm coverage`. Counts are derived from each question’s',
  '> canonical solution (DuckDB spelling). ✅ = at least one question; ☐ = gap.',
  '> The **Snowflake** column flags where the Snowflake spelling differs from',
  '> DuckDB’s — i.e. where a dialect/transpile layer (ADR 0002) is needed for',
  '> true fidelity.',
  '',
  `**${covered}/${FEATURES.length} features covered** across ${questions.length} questions.`,
  '',
];

for (const category of CATEGORIES) {
  const catRows = rows.filter((r) => r.feature.category === category);
  if (!catRows.length) continue;
  lines.push(`## ${category}`, '');
  lines.push('| | Feature | Questions | Snowflake nuance |');
  lines.push('|---|---|--:|---|');
  for (const r of catRows) {
    const box = r.count > 0 ? '✅' : '☐';
    const nuance = r.feature.snowflake ? `⚠️ ${r.feature.snowflake}` : '';
    lines.push(`| ${box} | ${r.feature.label} | ${r.count} | ${nuance} |`);
  }
  lines.push('');
}

// Gaps summary (uncovered features), most useful for planning content.
const gaps = rows.filter((r) => r.count === 0).map((r) => `${r.feature.category} → ${r.feature.label}`);
lines.push('## Gaps (0 questions)', '');
lines.push(gaps.length ? gaps.map((g) => `- ${g}`).join('\n') : '_None — full coverage._', '');

const out = new URL('../../COVERAGE.md', import.meta.url);
writeFileSync(out, lines.join('\n'));
console.log(`Coverage: ${covered}/${FEATURES.length} features covered. Wrote ${out.pathname}`);
for (const r of rows.filter((x) => x.count === 0)) console.log(`  ☐ ${r.feature.category} → ${r.feature.label}`);
