/**
 * Generates src/content/question-metadata.generated.ts by serialising each
 * question's canonical solution to a parse tree (DuckDB) and extracting
 * structural metrics. Run: pnpm meta:generate
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import * as duckdb from '@duckdb/duckdb-wasm/dist/duckdb-node-blocking.cjs';
import { extractMetrics } from '../src/content/metrics';
import { questions } from '../src/content/node';

const require = createRequire(import.meta.url);
const BUNDLES = {
  mvp: {
    mainModule: require.resolve('@duckdb/duckdb-wasm/dist/duckdb-mvp.wasm'),
    mainWorker: require.resolve('@duckdb/duckdb-wasm/dist/duckdb-node-mvp.worker.cjs'),
  },
  eh: {
    mainModule: require.resolve('@duckdb/duckdb-wasm/dist/duckdb-eh.wasm'),
    mainWorker: require.resolve('@duckdb/duckdb-wasm/dist/duckdb-node-eh.worker.cjs'),
  },
};

const db = await duckdb.createDuckDB(BUNDLES, new duckdb.VoidLogger(), duckdb.NODE_RUNTIME);
await db.instantiate(() => {});
const conn = db.connect();

function astOf(query: string): string {
  const escaped = query.replace(/'/g, "''");
  const table = conn.query(`SELECT json_serialize_sql('${escaped}') AS ast`);
  return (table.toArray()[0] as { ast: string }).ast;
}

const lines = questions.map((q) => {
  const metrics = extractMetrics(astOf((q.canonical.generic ?? '').trim()));
  return `  ${JSON.stringify(q.id)}: ${JSON.stringify(metrics)},`;
});

const file =
  `// AUTO-GENERATED by \`pnpm meta:generate\` — do not edit by hand.\n` +
  `// Structural metrics derived from each question's canonical solution.\n` +
  `import type { QuestionMetrics } from './metrics';\n\n` +
  `export const questionMetadata: Record<string, QuestionMetrics> = {\n` +
  `${lines.join('\n')}\n};\n`;

const out = new URL('../src/content/question-metadata.generated.ts', import.meta.url);
writeFileSync(out, file);
console.log(`Wrote metadata for ${questions.length} questions → ${out.pathname}`);
